### PR TITLE
Create MustBeEmailAddress extension method

### PR DESCRIPTION
**Pull request by johanvergeer**
Creating the regex took some time, but I think this can be vary beneficial for quite some people.

### CODE REVIEW

**Comment by johanvergeer** [comment]
I accently pushed my changed where I removed the net35 and net35-cf TargetFrameworks. I have corrected this mistake

**Comment by feO2x** [comment]
Thanks for your quick pull request. Unfortunately, I'm currently not at home - I'll probably merge on Friday.

**Comment by feO2x** [comment]
If everything is fine, I'll push on Friday, too.

**Comment by feO2x** [comment]
I merged your PR, but I had some issues with it:

- First of all, the `Light.GuardClauses.csproj` file couldn't be loaded by VS2017. There seems to be a hidden symbol at the beginning which I removed (see image).
- Furthermore, you explicitly referenced JetBrains.Annotations.dll. Light.GuardClauses should not have any references to other DLLs, so I removed them. The required `ContractAnntoationAttribute` for ReSharper Interop is specified in ResharperAnnotations.cs.
- I removed the `AutoGenerateBindingRedirects` statement as Light.GuardClauses does not depend on any third-party-DLLs

Issues in Light.GuardClauses.csproj

The rest is fine  :+1: I've added an overload to custom support exception factories and an overload that allows specifying a custom regular expression. Furthermore, the regex for emails is now statically cached, as this reduces the execution time drastically and puts less pressure on the GC:

BenchmarkDotNet results for IsEmailAddress

(`AllocatingVersionValidEmail` and `AllocatingVersionInvalidEmail` are testing your implementation version)

**Pull request merged**
